version: '3'

services:
  payload:
    build: .
    ports:
      - "${ZABO_EMBED_PORT}:3000"
    volumes:
      - ./assets:/home/node/app/assets
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      SERVER_URL: ${SERVER_URL}
      PORT: ${ZABO_EMBED_PORT}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}

  mongo:
    image: mongo:5.0
    command:
      - --storageEngine=wiredTiger
    volumes:
      - zabo-embed-data:/data/db
    logging:
      driver: none

volumes:
  zabo-embed-data:
    external: true

